name: Development checks

on:
  push:
    branches:
      - development
      - master

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: pre-commit hooks
        run: |
          python -m pip install pre-commit
          pre-commit install
          pre-commit run --all-files
      - name: Make migrations
        run: python manage.py makemigrations
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
          POSTGRES_HOST: "127.0.0.1"
      - name: Migrate
        run: python manage.py migrate
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
          POSTGRES_HOST: "127.0.0.1"
      - name: Run Tests
        run: |
          pytest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
          POSTGRES_HOST: "127.0.0.1"

  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [3.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          cd frontend/
          npm install
      - name: build module webpack
        run: |
          cd frontend/
          npm run dev
      - name: Run Tests
        run: |
          cd frontend/
          npm test
