name: Frontend Continuos Integration

on: [pull_request]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        cd frontend/
        npm install
    - name: build module webpack
      run: |
        cd frontend/
        npm run dev
    - name: Run Tests
      run: |
        cd frontend/
        npm test
